//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beans
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    [Serializable]
    public partial class module2
    {
        public module2()
        {
            this.Enseignants = new HashSet<Enseignant>();
            this.ModuleEtudies = new HashSet<ModuleEtudie>();
            this.Seance2 = new HashSet<Seance2>();
        }

        //[Browsable(false)]
        public int id_module { get; set; }
        public string nom_module { get; set; }
        public string abrv_module { get; set; }
        [Browsable(false)]
        public int coefficient { get; set; }

        [Browsable(false)]
        public virtual ICollection<Enseignant> Enseignants { get; set; }
        [Browsable(false)]
        public virtual ICollection<ModuleEtudie> ModuleEtudies { get; set; }
        [Browsable(false)]
        public virtual ICollection<Seance2> Seance2 { get; set; }
    }
}
