//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        public Etudiant()
        {
            this.Etudiant1 = new HashSet<Etudiant>();
            this.ModuleEtudies = new HashSet<ModuleEtudie>();
            this.RarFiles = new HashSet<RarFile>();
            this.SeanceAssistes = new HashSet<SeanceAssiste>();
        }
    
        public int id_etudiant { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int groupe { get; set; }
        public Nullable<int> id_binome { get; set; }
    
        public virtual ICollection<Etudiant> Etudiant1 { get; set; }
        public virtual Etudiant Etudiant2 { get; set; }
        public virtual ICollection<ModuleEtudie> ModuleEtudies { get; set; }
        public virtual ICollection<RarFile> RarFiles { get; set; }
        public virtual ICollection<SeanceAssiste> SeanceAssistes { get; set; }
    }
}
