//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seance2
    {
        public Seance2()
        {
            this.RarFiles = new HashSet<RarFile>();
            this.SeanceAssistes = new HashSet<SeanceAssiste>();
        }
    
        public int id_seance { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> id_enseignant { get; set; }
        public Nullable<int> id_module { get; set; }
        public byte[] Data { get; set; }
        public string Extension { get; set; }
        public string FileName { get; set; }
    
        public virtual Enseignant Enseignant { get; set; }
        public virtual module2 module2 { get; set; }
        public virtual ICollection<RarFile> RarFiles { get; set; }
        public virtual ICollection<SeanceAssiste> SeanceAssistes { get; set; }
    }
}
